import type { Inspection } from '../types';
import { InspectionStatus, InspectionSource, InspectionType, InspectionAction } from '../types';

export const mockInspections: Inspection[] = [
    {
        id: '1',
        protocol: '2024-001',
        address: 'Rua das Flores, 123, Centro, Governador Valadares, MG',
        latitude: -18.8516,
        longitude: -41.9495,
        source: InspectionSource.CITIZEN_WHATSAPP,
        type: InspectionType.CONSTRUCTION_PERMIT,
        description: 'Construção de muro sem aparente alvará de licença.',
        status: InspectionStatus.PENDING_FOLLOW_UP,
        createdAt: '2024-07-15T10:00:00Z',
        updatedAt: '2024-07-20T14:30:00Z',
        inspector: 'João Silva',
        report: 'Realizada diligência no local. Constatado o início de obras para construção de um muro de divisa. O proprietário não apresentou o alvará de licença. Foi notificado a paralisar a obra e regularizar a situação no prazo de 10 dias.',
        reportSummary: 'Proprietário notificado por construção irregular de muro sem alvará, com prazo de 10 dias para regularização.',
        photos: [],
        followUps: [
            { id: 'f1', date: '2024-07-30', notes: 'Verificar se a obra foi paralisada e se o proprietário iniciou o processo de regularização.', completed: false }
        ],
        actions: [InspectionAction.NOTIFICATION, InspectionAction.ORIENTED],
        verifiedInfractions: { [InspectionType.CONSTRUCTION_PERMIT]: true, [InspectionType.BOUNDARY_WALL]: true },
        complainantName: 'Maria Joaquina',
        complainantAddress: 'Rua das Orquídeas, 456, Centro, Governador Valadares, MG',
        respondentName: 'José da Silva',
        contactPhone: '(33) 99999-8888',
        attachments: [],
        referencePoint: 'Ao lado da padaria Pão Quente',
        complaintDate: '2024-07-14',
        history: [
            { timestamp: '2024-07-20T14:30:00Z', user: 'João Silva', change: 'Agendamento de retorno criado para 30/07/2024.' },
            { timestamp: '2024-07-20T14:25:00Z', user: 'João Silva', change: 'Relatório da constatação foi atualizado.' },
            { timestamp: '2024-07-18T11:00:00Z', user: 'João Silva', change: 'Status alterado de Em Análise para Em Andamento.' },
            { timestamp: '2024-07-15T10:05:00Z', user: 'Sistema', change: 'Fiscal João Silva foi atribuído.' },
            { timestamp: '2024-07-15T10:00:00Z', user: 'Sistema', change: 'Chamado criado.' },
        ],
    },
    {
        id: '2',
        protocol: '2024-002',
        address: 'Av. Brasil, 2045, Bairro Industrial, Governador Valadares, MG',
        latitude: -18.8622,
        longitude: -41.9588,
        source: InspectionSource.PUBLIC_MINISTRY,
        type: InspectionType.MATERIALS_ON_STREET,
        description: 'Denúncia de material de construção (areia e brita) obstruindo a calçada e parte da via pública.',
        status: InspectionStatus.IN_PROGRESS,
        createdAt: '2024-07-18T09:30:00Z',
        updatedAt: '2024-07-19T11:00:00Z',
        inspector: 'Maria Oliveira',
        report: 'Visita ao local confirmou a presença de materiais de construção na calçada, dificultando a passagem de pedestres. O responsável pela obra foi notificado para remover o material em 24 horas.',
        photos: [],
        followUps: [],
        actions: [InspectionAction.NOTIFICATION],
        verifiedInfractions: { [InspectionType.MATERIALS_ON_STREET]: true },
        attachments: [],
        referencePoint: '',
        complaintDate: '2024-07-17',
        history: [
            { timestamp: '2024-07-19T11:00:00Z', user: 'Maria Oliveira', change: 'Relatório da constatação foi atualizado e ações foram registradas.' },
            { timestamp: '2024-07-18T09:30:00Z', user: 'Sistema', change: 'Chamado criado.' },
        ],
    },
    {
        id: '3',
        protocol: '2024-003',
        address: 'Praça Serra Lima, 50, Centro, Governador Valadares, MG',
        latitude: -18.8509,
        longitude: -41.9481,
        source: InspectionSource.INTERNAL,
        type: InspectionType.BUSINESS_PERMIT,
        description: 'Verificação de rotina de alvará de funcionamento de novo restaurante.',
        status: InspectionStatus.CLOSED,
        createdAt: '2024-07-20T14:00:00Z',
        updatedAt: '2024-07-21T16:00:00Z',
        inspector: 'João Silva',
        report: 'Estabelecimento apresentou toda a documentação necessária, incluindo alvará de funcionamento válido. Nenhuma irregularidade constatada. Processo arquivado.',
        photos: [],
        followUps: [],
        actions: [InspectionAction.ORIENTED],
        verifiedInfractions: { [InspectionType.BUSINESS_PERMIT]: false, [InspectionType.OCCUPANCY_PERMIT]: false },
        attachments: [],
        referencePoint: 'Em frente à prefeitura',
        complaintDate: '2024-07-19',
        history: [
            { timestamp: '2024-07-21T16:00:00Z', user: 'João Silva', change: 'Status alterado de Em Andamento para Concluído.' },
            { timestamp: '2024-07-20T14:00:00Z', user: 'Sistema', change: 'Chamado criado.' },
        ],
    },
    {
        id: '4',
        protocol: '2024-004',
        address: 'Rua dos Pinheiros, 789, Vila Nova, Governador Valadares, MG',
        latitude: -18.8450,
        longitude: -41.9600,
        source: InspectionSource.OMBUDSMAN,
        type: InspectionType.OCCUPANCY_PERMIT,
        description: 'Imóvel residencial sendo utilizado para fins comerciais sem o devido Alvará de Ocupação.',
        status: InspectionStatus.UNDER_REVIEW,
        createdAt: '2024-07-22T11:20:00Z',
        updatedAt: '2024-07-22T11:20:00Z',
        inspector: 'Ana Costa',
        report: '',
        photos: [],
        followUps: [],
        actions: [],
        verifiedInfractions: {},
        attachments: [],
        referencePoint: '',
        complaintDate: '2024-07-21',
        history: [
            { timestamp: '2024-07-22T11:20:00Z', user: 'Sistema', change: 'Chamado criado e atribuído para Ana Costa.' },
        ],
    },
];